sudo: required
services:
  - docker

before_install:
  - docker build -t dockertravisreact -f Dockerfile.dev .

script:
  - docker run dockertravisreact npm run test -- --coverage #-e CI=true without -- --coverage